language: d

sudo: false

d:
  - dmd #-2.071.0
  - dmd-2.070.2
  - dmd-2.069.2
  - dmd-2.068.1
  - dmd-2.067.1
  - dmd-2.066.1
  - dmd-2.065.0
  - ldc-0.14.0
  - ldc-0.15.1
  - ldc-0.16.1
  - ldc #-0.17.1
  #- ldc-1.0.0-beta1
  - gdc #-5.2.0
  - gdc-4.9.3
  - gdc-4.9.2
  - gdc-4.9.0
  - gdc-4.8.2

script:
  - dub test --compiler=$DC || exit 1
